/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TermsofserviceLazyImport = createFileRoute('/termsofservice')()
const SettingsLazyImport = createFileRoute('/settings')()
const PrivacypolicyLazyImport = createFileRoute('/privacypolicy')()
const GamesLazyImport = createFileRoute('/games')()
const FaqLazyImport = createFileRoute('/faq')()
const ChangelogLazyImport = createFileRoute('/changelog')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const GameGameLazyImport = createFileRoute('/game/$game')()

// Create/Update Routes

const TermsofserviceLazyRoute = TermsofserviceLazyImport.update({
  path: '/termsofservice',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/termsofservice.lazy').then((d) => d.Route),
)

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const PrivacypolicyLazyRoute = PrivacypolicyLazyImport.update({
  path: '/privacypolicy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/privacypolicy.lazy').then((d) => d.Route))

const GamesLazyRoute = GamesLazyImport.update({
  path: '/games',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/games.lazy').then((d) => d.Route))

const FaqLazyRoute = FaqLazyImport.update({
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))

const ChangelogLazyRoute = ChangelogLazyImport.update({
  path: '/changelog',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/changelog.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GameGameLazyRoute = GameGameLazyImport.update({
  path: '/game/$game',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game.$game.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/changelog': {
      preLoaderRoute: typeof ChangelogLazyImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      preLoaderRoute: typeof FaqLazyImport
      parentRoute: typeof rootRoute
    }
    '/games': {
      preLoaderRoute: typeof GamesLazyImport
      parentRoute: typeof rootRoute
    }
    '/privacypolicy': {
      preLoaderRoute: typeof PrivacypolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/termsofservice': {
      preLoaderRoute: typeof TermsofserviceLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$game': {
      preLoaderRoute: typeof GameGameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  ChangelogLazyRoute,
  FaqLazyRoute,
  GamesLazyRoute,
  PrivacypolicyLazyRoute,
  SettingsLazyRoute,
  TermsofserviceLazyRoute,
  GameGameLazyRoute,
])

/* prettier-ignore-end */
