# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - run: ls
    - run: cd starter-frontend
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls
    - run: cd starter-frontend
    - run: ls
    - name: Install dependencies
      run: npm install
    - run: npm run build
     # deploy the react app to github pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # directory to deploy
    
